// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventCallback is an autogenerated mock type for the EventCallback type
type EventCallback struct {
	mock.Mock
}

// Event provides a mock function with given fields: result
func (_m *EventCallback) Event(result string) {
	_m.Called(result)
}
