// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HostCallbacks is an autogenerated mock type for the HostCallbacks type
type HostCallbacks struct {
	mock.Mock
}

// OnListening provides a mock function with given fields: id, err
func (_m *HostCallbacks) OnListening(id string, err string) {
	_m.Called(id, err)
}

// OnPeersDiscovered provides a mock function with given fields: peersIds
func (_m *HostCallbacks) OnPeersDiscovered(peersIds []string) {
	_m.Called(peersIds)
}
