// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "peeral.com/proxy-libp2p/domain/models"
)

// IServerRepository is an autogenerated mock type for the IServerRepository type
type IServerRepository struct {
	mock.Mock
}

// Connect provides a mock function with given fields: login, pwd
func (_m *IServerRepository) Connect(login string, pwd string) error {
	ret := _m.Called(login, pwd)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(login, pwd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: name
func (_m *IServerRepository) Create(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Join provides a mock function with given fields: name
func (_m *IServerRepository) Join(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessage provides a mock function with given fields: message
func (_m *IServerRepository) SendMessage(message *models.MessageDto) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.MessageDto) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
